<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Diario.Data\Diario.Data.csproj" />
    <ProjectReference Include="..\Diario.Model\Diario.Model.csproj" />
  </ItemGroup>

</Project>
