<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\diario.business\diario.business.csproj" />
    <ProjectReference Include="..\diario.data\diario.data.csproj" />
    <ProjectReference Include="..\diario.model\diario.model.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
